<?php

/**
 * Implements hook_wizard_info
 */
function wizard_helper_sample_wizard_info() {
  $wizards = array();

  /**
   * Define our wizard.
   *
   * Important note:  The key to this array is also used as a key to define
   * a hook_menu item that will be used for the wizard callback.
   */
  $wizards['mywizard'] = array(
    'title' => 'My Wizard',
    'pages' => array(
      'page1' => 'Page 1',
      'page2' => 'Page 2',
      'page3' => 'Page 3'
    )
  );

  return $wizards;
}

/**
 * Called when the wizard "mywizard" is complete.
 */
function wizard_helper_sample_mywizard_finish(&$form_state) {
  // Process your form and save something here.
  $object = $form_state['mywizard'];
}
?>