<?php
/**
 * This module works to help reduce code complexity and increase code reuse by
 * using a hook system to define your CTools wizard.  Here is how to use this module.
 *
 * Within you module, implement hook_wizard_info, which should return the following.
 *
 * function hook_wizard_info
 */

/**
 * Returns the wizard information.
 */
function wizard_helper_info() {
  static $info = array();
  if (!$info) {
    if ($cache = cache_get('wizard_helper_info')) {
      $info = $cache->data;
    }
    else {
      $info = array();

      // Get the wizard information from other modules.
      foreach (module_implements('wizard_info') as $module) {
        $function = $module .'_wizard_info';
        $result = $function();
        foreach ($result as $path => &$wizard) {
          $wizard['module'] = $module;
          $wizard['path'] = $path;
          $wizard['id'] = isset($wizard['id']) ? $wizard['id'] : str_replace('/', '_', $path);
          $wizard['pages'] = isset($wizard['pages']) ? $wizard['pages'] : array();
          $wizard['title'] = isset($wizard['title']) ? $wizard['title'] : '';
          $wizard['access callback'] = isset($wizard['access callback']) ? $wizard['access callback'] : 'user_access';
          $wizard['access arguments'] = isset($wizard['access arguments']) ? $wizard['access arguments'] : array('access content');
          $wizard['title'] = isset($wizard['title']) ? $wizard['title'] : '';
          $wizard['wizard_path'] = isset($wizard['wizard_path']) ? $wizard['wizard_path'] : drupal_get_path('module', $module) . '/' . $wizard['id'];
          $wizard['form id'] = isset($wizard['form id']) ? $wizard['form id'] : $wizard['module'] . '_' . $wizard['id'];
          $wizard['object name'] = isset($wizard['object name']) ? $wizard['object name'] : $wizard['form id'];
          $wizard['pageids'] = isset($wizard['pageids']) ? $wizard['pageids'] : array();
          $wizard['cancel path'] = isset($wizard['cancel path']) ? $wizard['cancel path'] : $path;
          $wizard['return path'] = isset($wizard['return path']) ? $wizard['return path'] : $path;
          $wizard['access'] = TRUE;

          // Iterate though the pages and assign page ids.
          if (!empty($wizard['pages'])) {
            foreach ($wizard['pages'] as $page => $title) {
              if (!isset($wizard['pageids'][$page])) {
                $wizard['pageids'][$page] = $wizard['form id'] . '_' . $page;
              }
            }
          }
        }
        $info = array_merge($info, $result);
      }

      // Allow others to alter the information.
      drupal_alter('wizard_info', $info);

      // Set this in cache.
      cache_set('wizard_helper_info', $info);
    }
  }
  return $info;
}

/**
 * Implements hook_menu().
 */
function wizard_helper_menu() {
  $items = array();
  $info = wizard_helper_info();
  foreach ($info as $path => $wizard) {
    $parts = explode('/', $path);
    $index = count($parts);
    $items[$path] = array(
      'title' => $wizard['title'],
      'page callback' => 'wizard_helper_wizard',
      'page arguments' => array($index, ($index + 1)),
      'access callback' => $wizard['access callback'],
      'access arguments' => $wizard['access arguments'],
      'type' => MENU_CALLBACK,
    );
    $items[$path . '/%/%ctools_js'] = $items[$path];
  }
  return $items;
}

/**
 * Implements hook_theme().
 */
function wizard_helper_theme() {
  $themes = array();

  // Get the wizard information.
  $info = wizard_helper_info();

  // Iterate through all wizards.
  foreach ($info as $path => $wizard) {

    // Get all the wizard helper page ids.
    foreach( $wizard['pageids'] as $page => $id ) {

      // Add the template if the file exists.
      if (file_exists(getcwd() . '/' . $wizard['wizard_path'] . '/' . $id . '.tpl.php')) {

        // Add the template.
        $themes[$id] = array(
          'template'  => $id,
          'path' => $wizard['wizard_path'],
          'arguments' => array('form' => NULL )
        );
      }
    }
  }

  // Return the themes.
  return $themes;
}

/**
 * This function will include a form from the wizard_helper.
 */
function wizard_helper_include_form($form_id) {
  // Get the wizard information.
  $info = wizard_helper_info();
  foreach ($info as $path => $wizard) {
    foreach( $wizard['pageids'] as $page => $id ) {
      if ($id == $form_id) {
        $file = getcwd() . '/' . $wizard['wizard_path'] . '/' . $id . '.inc';
        if (file_exists($file)) {
          require_once $file;
        }
        break;
      }
    }
  }
}

/**
 * Implements hook_forms
 */
function wizard_helper_forms($form_id, $args) {
  $forms = array();
  $info = wizard_helper_info();
  foreach ($info as $path => $wizard) {
    foreach( $wizard['pageids'] as $page => $id ) {
      $forms[$id] = array(
        'callback' => 'wizard_helper_page_form',
        'callback arguments' => array($form_id, $args)
      );
    }
  }
  return $forms;
}

/**
 * Load function for the wizard.
 */
function wizard_helper_load($path) {
  $info = wizard_helper_info();
  $wizard = $info[$path];
  $wizard['object'] = wizard_helper_cache_get($wizard);
  return $wizard;
}


/**
 * Returns the wizard information for this path.
 */
function wizard_helper_get_info() {
  $item = menu_get_item();
  return wizard_helper_load(rtrim($item['path'], '/%'));
}

/**
 * Adds a common form function for all wizard forms.  This fixes several
 * issues with adding AHAH within your forms.
 */
function wizard_helper_page_form(&$form_state, $form_id, $args) {
  // Include the form.
  $form = array();
  ctools_include('wizard');
  ctools_wizard_wrapper($form, $form_state);
  wizard_helper_include_form($form_id);
  if (function_exists($form_id)) {
    $form_id($form, $form_state);
  }
  return $form;
}

function wizard_helper_form($wizard, $step, $js, $form_state = array()) {
  // Include the ctools wizard stuff.
  ctools_include('wizard');
  ctools_include('ajax');

  // Setup the form_state.
  $form_state = array_merge(array(
    $wizard['object name'] => $wizard['object'],
    'wizard_info' => $wizard,
    'title' => $wizard['title'],
    'ajax' => $js
  ), $form_state);

  // Set the pages.
  $pages = $wizard['pages'];

  // Return nothing if there are no pages.
  if (empty($pages)) {
    return array();
  }

  // Set all the pages for this wizard.
  $forms = array();
  foreach( $wizard['pageids'] as $page => $id ) {
    $forms[$page] = array('form id' => $id);
    $file = $wizard['wizard_path'] . '/' . $id . '.inc';
    if (file_exists(getcwd() . '/' . $file)) {
      $forms[$page]['include'] = $file;
    }
  }

  // Setup our CTools multistep form.
  $form_info = array(
    'id' => $wizard['form id'],
    'path' => $wizard['path'] . "/%step/" . ($js ? 'ajax' : 'nojs'),
    'next callback' =>  'wizard_helper_next',
    'finish callback' => 'wizard_helper_finish',
    'return callback' => 'wizard_helper_finish',
    'cancel callback' => 'wizard_helper_cancel',
    'order' => $pages,
    'forms' => $forms
  );

  // Setup the defaults for the wizard information.
  $defaults = array(
    'show trail' => TRUE,
    'show back' => TRUE,
    'show cancel' => TRUE,
    'show return' => FALSE,
    'cancel path' => '',
    'return path' => ''
  );

  // Add the defaults to the form, and then bring in those values from the
  // wizard.
  $form_info = array_merge(
    array_merge($form_info, $defaults),
    array_intersect_key($wizard, $defaults)
  );

  // If there is no step, then set it to the first item in the array.
  if (!$step) {
    reset($pages);
    $step = key($pages);
  }

  // Create our multistep drupal form.
  return ctools_wizard_multistep_form($form_info, $step, $form_state);
}

/**
 * Get the correct context.
 *
 * @return {string} The step for the user.
 */
function wizard_helper_set_context($wizard, $step, $js) {
  global $user;

  // We only do this for valid sessions.
  if (!empty($user->sid)) {

    // If no step is provided, but they have a previous context, then send them
    // to the correct spot and provide a message if need be.
    if (!$step && !empty($wizard['object']) && $wizard['object']['step']) {

      // If the wizard wishes to say something to the user.
      if (!empty($wizard['restore message'])) {

        // Print a message so they know what is up.
        drupal_set_message($wizard['restore message']);
      }

      // Now goto the correct context.
      drupal_goto($wizard['path'] . '/' . $wizard['object']['step'] . '/' . ($js ? $js : 'nojs'));
    }

    // On the flip side, if they go to a step, but do not have context, then
    // send them back to the beginning.
    if ($step && empty($wizard['object'])) {

      // Go to the original path.
      drupal_goto($wizard['path']);
    }
  }
}

/**
 * Wizard callback function.
 */
function wizard_helper_wizard($step = '', $js = '') {

  // Get the wizard information for this path.
  if ($wizard = wizard_helper_get_info()) {

    // Set the correct context for this wizard.
    wizard_helper_set_context($wizard, $step, $js);

    // Make sure we have a context object defined.
    if (empty($wizard['object'])) {
      $wizard['object'] = array();
    }

    // Call the wizard callback to alter the info at runtime.
    if (isset($wizard['wizard callback'])) {
      $function = $wizard['wizard callback'];
      $function($step, $wizard);
    }

    // Set the current context.
    if ($step && (empty($wizard['object']['step']) || ($step != $wizard['object']['step']))) {
      $wizard['object']['step'] = $step;
      wizard_helper_cache_set($wizard, $wizard['object']);
    }

    // Make sure there are pages.
    if (empty($wizard['pages'])) {
      drupal_not_found();
      return;
    }

    // Make sure we have access.
    if (empty($wizard['access'])) {
      drupal_access_denied();
      return;
    }

    // If there is already output, then return it here.
    if (!empty($wizard['output'])) {
      return $wizard['output'];
    }

    // Return the wizard helper form.
    return wizard_helper_form($wizard, $step, $js);
  }

  // Return 404 if we cannot find the information.
  drupal_not_found();
}

/**
 * Go to a page within the wizard without it resetting context.
 */
function wizard_helper_goto($wizard, $step = '') {
  $wizard['object']['step'] = $step;
  wizard_helper_cache_set($wizard, $wizard['object']);
  $path = $wizard['path'];
  $path .= $step ? '/' . $step : '';
  drupal_goto($path);
}

/**
 * Set the object cache.
 */
function wizard_helper_cache_set($wizard, $value) {
  ctools_include('object-cache');
  ctools_object_cache_set('wizard_helper', $wizard['object name'], $value);
}

/**
 * Get the object cache.
 */
function wizard_helper_cache_get($wizard) {
  ctools_include('object-cache');
  return ctools_object_cache_get('wizard_helper', $wizard['object name']);
}

/**
 * Clear the object cache.
 */
function wizard_helper_cache_clear($wizard) {
  ctools_include('object-cache');
  ctools_object_cache_clear('wizard_helper', $wizard['object name']);
}

/**
 * Callback for the proceed step
 */
function wizard_helper_next(&$form_state) {
  $wizard = $form_state['wizard_info'];
  wizard_helper_cache_set($wizard, $form_state[$wizard['object name']]);
}

/**
 * Callback generated when the wizard is finished.
 */
function wizard_helper_finish(&$form_state) {
  $wizard = $form_state['wizard_info'];
  wizard_helper_cache_clear($wizard);
  $function = $wizard['wizard finish'];
  if (function_exists($function)) {
    $function($form_state[$wizard['object name']]);
  }
  $form_state['complete'] = TRUE;
}

/**
 * Callback for the cancel.
 */
function wizard_helper_cancel(&$form_state) {
  $wizard = $form_state['wizard_info'];
  wizard_helper_cache_clear($wizard);
  if (!empty($wizard['cancel message'])) {
    drupal_set_message($wizard['cancel message']);
  }
  $form_state['cancel'] = TRUE;
}
