<?php
/**
 * This module works to help reduce code complexity and increase code reuse by
 * using a hook system to define your CTools wizard.  Here is how to use this module.
 *
 * Within you module, implement hook_wizard_info, which should return the following.
 *
 * function hook_wizard_info
 */


include_once 'includes/wizard_helper_preprocess.inc';

/**
 * Returns the wizard information.
 */
function wizard_helper_info() {
  static $info = array();
  if (!$info) {
    if ($cache = cache_get('wizard_helper_info')) {
      $info = $cache->data;

      // Allow others to alter the information.
      drupal_alter('wizard_info', $info);
    }
    else {
      $info = array();

      // Get the wizard information from other modules.
      foreach (module_implements('wizard_info') as $module) {
        $function = $module . '_wizard_info';
        $result = $function();
        foreach ($result as $path => &$wizard) {
          $wizard['module'] = $module;
          $wizard['path'] = $path;
          $wizard['id'] = isset($wizard['id']) ? $wizard['id'] : str_replace('/', '_', $path);
          $wizard['pages'] = isset($wizard['pages']) ? $wizard['pages'] : array();
          $wizard['title'] = isset($wizard['title']) ? $wizard['title'] : '';
          $wizard['access callback'] = isset($wizard['access callback']) ? $wizard['access callback'] : 'user_access';
          $wizard['access arguments'] = isset($wizard['access arguments']) ? $wizard['access arguments'] : array('access content');
          $wizard['wizard path'] = isset($wizard['wizard path']) ? $wizard['wizard path'] : $wizard['id'];
          $wizard['module path'] = isset($wizard['module path']) ? $wizard['module path'] : drupal_get_path('module', $module) . '/' . $wizard['wizard path'];
          $wizard['form id'] = isset($wizard['form id']) ? $wizard['form id'] : $wizard['module'] . '_' . $wizard['id'];
          $wizard['object name'] = isset($wizard['object name']) ? $wizard['object name'] : $wizard['form id'];
          $wizard['context id'] = 0;
          $wizard['theme'] = isset($wizard['theme']) ? $wizard['theme'] : 'wizard_helper_page';
          $wizard['pageids'] = isset($wizard['pageids']) ? $wizard['pageids'] : array();
          $wizard['cancel path'] = isset($wizard['cancel path']) ? $wizard['cancel path'] : $path;
          $wizard['return path'] = isset($wizard['return path']) ? $wizard['return path'] : $path;
          $wizard['complete path'] = isset($wizard['complete path']) ? $wizard['complete path'] : $path;
          $wizard['cache type'] = isset($wizard['cache type']) ? $wizard['cache type'] : 'session';
          $wizard['register'] = isset($wizard['register']) ? $wizard['register'] : FALSE;

          // Iterate though the pages and assign page ids.
          if (!empty($wizard['pages'])) {
            foreach ($wizard['pages'] as $page => $data) {
              if (!isset($wizard['pageids'][$page])) {
                $wizard['pageids'][$page] = $wizard['form id'] . '_' . $page;
              }
            }
          }

          reset($wizard['pages']);
          // This key is our starting point.
          $wizard['start'] =  key($wizard['pages']);
        }
        $info = array_merge($info, $result);
      }

      // Allow others to alter the information.
      drupal_alter('wizard_info', $info);

      // Set this in cache.
      cache_set('wizard_helper_info', $info);
    }
  }
  return $info;
}

/**
 * Implements hook_menu().
 */
function wizard_helper_menu() {
  $items = array();
  $info = wizard_helper_info();
  foreach ($info as $path => $wizard) {
    $parts = explode('/', $path);
    $index = count($parts);
    $items[$path] = array(
      'title' => $wizard['title'],
      'page callback' => 'wizard_helper_wizard',
      'page arguments' => array($index, ($index + 1)),
      'access callback' => $wizard['access callback'],
      'access arguments' => $wizard['access arguments'],
      'type' => MENU_CALLBACK,
    );
    $items[$path . '/%/%ctools_js'] = $items[$path];
  }
  return $items;
}

/**
 * Implements hook_theme().
 */
function wizard_helper_theme() {
  $themes = array();

  // Get the wizard information.
  $info = wizard_helper_info();

  // Iterate through all wizards.
  foreach ($info as $path => $wizard) {

    // Get all the wizard helper page ids.
    foreach ($wizard['pageids'] as $page => $id) {

      $file = DRUPAL_ROOT . '/' . $wizard['module path'] . '/' . $id . '.tpl.php';
      // Add the template if the file exists.
//      if (file_exists(getcwd() . '/' . $wizard['wizard path'] . '/' . $id . '.tpl.php')) {
      if (file_exists(DRUPAL_ROOT . '/' . $wizard['module path'] . '/' . $id . '.tpl.php')) {

        // Add the template.
        $themes[$id] = array(
          'render element' => 'form',
          'template'  => $id,
          'path' => $wizard['module path'],
        );
      }
    }
  }

  // Add a 'wrapper' template for the wizard. This defaults to 'wizard_helper_page'.
  $themes[$wizard['theme']] = array(
    'render element' => 'form',
    'template' => $wizard['theme'],
    'path' => drupal_get_path('module', $wizard['module']) . '/theme',
  );

  // Return the themes.
  return $themes;
}

/**
 * This function will include a form from the wizard_helper.
 *
 * @param array $wizard
 *   The wizard settings object.
 * @param string $form_id
 *   The full name of the form file to include.
 */
function wizard_helper_include_form($wizard, $form_id) {
  if (in_array($form_id, $wizard['pageids'])) {
    $file = DRUPAL_ROOT . drupal_get_path('module', $wizard['module']) . '/' . $wizard['wizard path'] . '/' . $form_id . '.inc';
    if (file_exists($file)) {
      require_once $file;
    }
  }
}

/**
 * Implements hook_forms().
 */
function wizard_helper_forms($form_id, $args) {
  // @todo: Minimize what get called here if we can do an if($form_id)...
  $forms = array();
  $info = wizard_helper_info();
  foreach ($info as $path => $wizard) {
    foreach ($wizard['pageids'] as $page => $id) {
      $forms[$id] = array(
        'callback' => 'wizard_helper_page_form',
        'callback arguments' => array($form_id, $args),
      );
    }
  }
  return $forms;
}

/**
 * Adds a common form function for all wizard forms.  This fixes several
 * issues with adding AHAH within your forms.
 */
function wizard_helper_page_form(&$form_state, $form_id) {
  $wizard = $form_state['wizard_info'];
  // Include the form.
  $form = array();
  ctools_include('wizard');
  ctools_wizard_wrapper($form, $form_state);
  ctools_form_include($form_state, $form_id, $wizard['module'], $wizard['wizard path']);
  if (function_exists($form_id)) {
    $form_id($form, $form_state);
  }
  return $form;
}

/**
 * Load function for the wizard.
 */
function wizard_helper_load($path) {
  $info = wizard_helper_info();
  $wizard = $info[$path];
  $wizard['object'] = wizard_helper_cache_get($wizard);
  return $wizard;
}


/**
 * Returns the wizard information for this path.
 */
function wizard_helper_get_info() {
  $item = menu_get_item();
  return wizard_helper_load(rtrim($item['path'], '/%'));
}

/**
 * @param string $wizard
 * @param string $step
 * @param bool $js
 * @param array $form_state
 * @return string
 */
function wizard_helper_form(&$wizard, $step, $js, $form_state = array()) {
  // Include the ctools wizard stuff.
  if ($js) {
    ctools_include('modal');
    ctools_include('ajax');
    // Add CTools' javascript to the page.
    ctools_modal_add_js();
  }

  // Setup the form_state.
  $form_state = array_merge(array(
    $wizard['object name'] => $wizard['object'],
    'wizard_info' => $wizard,
    'title' => $wizard['title'],
    'ajax' => $js
  ), $form_state);

  // Set the pages.
  $pages = $wizard['pages'];

  // Return nothing if there are no pages.
  if (empty($pages)) {
    return array();
  }

  // Set all the pages for this wizard.
  $forms = array();
  foreach ($wizard['pageids'] as $page => $id ) {
    $forms[$page] = array('form id' => $id);
    $file = $wizard['module path'] . '/' . $id . '.inc';
    // @todo - this should only be checked when the for is created - wasting
    // cycles checking for files that are never loaded.
    if (file_exists(DRUPAL_ROOT . '/' . $file)) {
      $forms[$page]['include'] = $file;
    }
    // We need to add our form submit function. This gets added before
    // ctools_wizard_submit().
    $forms[$page]['submit'] = 'wizard_helper_submit';

    // Include custom wrapper functions that can be used to alter the form before
    // ctools_wizard_wrapper() returns it.
    $forms[$page]['wrapper'] = $wizard['form id'] . '_wrapper';
  }

  // Setup our CTools multistep form.
  $form_info = array(
    'id' => $wizard['form id'],
    'path' => $wizard['path'] . "/%step/" . ($js ? 'ajax' : 'nojs'),
    'next callback' => 'wizard_helper_next',
    'finish callback' => 'wizard_helper_finish',
    'return callback' => 'wizard_helper_finish',
    'cancel callback' => 'wizard_helper_cancel',
    'order' => $pages,
    'forms' => $forms
  );

  // Setup the defaults for the wizard information.
  $defaults = array(
    'show trail' => TRUE,
    'show back' => TRUE,
    'show cancel' => TRUE,
    'show return' => FALSE,
    'cancel path' => '',
    'return path' => ''
  );

  // Add the defaults to the form, and then bring in those values from the
  // wizard.
  $form_info = array_merge(
    array_merge($form_info, $defaults),
    array_intersect_key($wizard, $defaults)
  );

  // Allow editing the form info.
  drupal_alter('wizard_helper_form', $form_info);

  // Store the registration object in $_SESSION.
  if (!isset($_SESSION[$wizard['object name']])) {
    $_SESSION[$wizard['object name']] = $wizard['object'];
  }
  else {
    $_SESSION[$wizard['object name']] = array_merge($_SESSION[$wizard['object name']], $wizard['object']);
  }

  // @todo: Figure out why this breaks the prev button (Back).
  $form_info['wrapper'] = 'wizard_helper_wrapper';

  // Establish the form state if it is provided.
  if (!empty($wizard['form_state'])) {
    $form_state = array_merge_recursive($form_state, $wizard['form_state']);
  }

  // Create our multistep drupal form.
  ctools_include('wizard');
  $form = ctools_wizard_multistep_form($form_info, $step, $form_state);

  // Add our page template.
  $form['#theme'] = array($wizard['theme']);

  // Render the output.
  $output = drupal_render($form);

  if ($js) {
    // If javascript is active, we have to use a render array.
    $commands = array();
    if ($output === FALSE || !empty($form_state['complete'])) {
      // @todo: This means there is no form and the wizard is complete. How do
      // @todo: we want to handle this for the wizard helper.
      $commands[] = ctools_modal_command_dismiss();
      $commands[] = ctools_ajax_command_redirect($wizard['complete path']);
    }
    else if (!empty($form_state['cancel'])) {
      // If cancelling, return to the activity.
      $commands[] = ctools_modal_command_dismiss();
      $commands[] = ctools_ajax_command_redirect($wizard['cancel path']);
    }
    else {
      $commands = ctools_modal_form_render($form_state, $output);
    }
    print ajax_render($commands);
    exit;
  }
  else {
    if ($output === FALSE || !empty($form_state['complete'])) {
      // @todo: This means there is no form and the wizard is complete. How do
      // @todo: we want to handle this for the wizard helper.
      drupal_goto($wizard['complete path']);
    }
    // The wizard has been cancelled.
    else if (!empty($form_state['cancel'])) {
      // If we have a cancel path send them there, otherwise send them to the
      // wizard path. This could be $wizard['wizard redirect'] if set in
      // hook_wizard_info() or it defaults to the path (key) of the wizard.
      drupal_goto($wizard['cancel path']);
    }
    else {
      return $output;
    }
  }
}

/**
 * A callback to modify the form just before it's built.
 *
 * @param array $form
 *   The form array.
 *
 * @param array $form_state
 *   The form_state array object.
 *
 * @return array
 *
 */
function wizard_helper_wrapper(&$form, &$form_state) {

  $wizard_name = $form_state['wizard_info']['object name'];
  $prev = wizard_helper_trail_previous($form_state['step'], $form_state[$wizard_name], $form_state['wizard_info']);
  if ($prev) {
    $form['buttons']['previous']['#next'] = $prev;
  }
  return $form;
}

/**
 * Called when a wizard form is submitted.
 *
 * @param array $form
 *   The wizard form.
 * @param array $form_state
 *   The form_state of the submission.
 */
function wizard_helper_submit(&$form, &$form_state) {

  // See if they clicked the next button.
  if (isset($form_state['clicked_button']['#wizard type']) && ($form_state['clicked_button']['#wizard type'] === 'next')) {

    // Get the wizard.
    $wizard = &$form_state['wizard_info'];

    // Set the object to the latest version.
    $wizard['object'] = &$form_state[$wizard['object name']];

    wizard_helper_cache_set($wizard, $wizard['object']);

    // See if this should be the next page.
    $next_page = wizard_helper_get_next_page($wizard, $form_state['clicked_button']['#next']);
    if ($next_page && $next_page !== $form_state['clicked_button']['#next']) {

      // See if this is in our pages array.
      if (isset($wizard['pages'][$next_page])) {
        $form_state['clicked_button']['#next'] = $next_page;
        $form_state['redirect'] = ctools_wizard_get_path($form_state['form_info'], $next_page);
      }
      else {

        // Otherwise, change our wizard type.
        $form_state['clicked_button']['#wizard type'] = $next_page;
      }
    }
  }
}

/**
 * Get the correct context.
 *
 * @return {string} The step for the user.
 */
function wizard_helper_set_context(&$wizard, $step, $js) {

  $object = $wizard['object'];

//  if (!empty($object) && !in_array($wizard['start'], $object['step_trail'])) {
//    wizard_helper_cache_clear($wizard);
//    drupal_goto($wizard['path'] . '/' . $wizard['start'] . '/' . ($js ? $js : 'nojs'));
//  }
  // We only do this for valid sessions.
  if (!empty($_SESSION[$wizard['object name']])) {

    // If no step is provided, but they have a previous context that isn't
    // on the start page, then send them to the correct spot and provide a
    // message if need be.
    if (!$step && !empty($object) && !empty($object['step']) && ($object['step'] != $wizard['start'])) {

      // If the wizard wishes to say something to the user.
      if (!empty($wizard['restore message'])) {

        // Print a message so they know what is up.
        drupal_set_message($wizard['restore message']);
      }

      // Now goto the correct context.
      drupal_goto($wizard['path'] . '/' . $object['step'] . '/' . ($js ? $js : 'nojs'));
    }
//    else if ($step && !empty($object) && !empty($object['step'])) {
//      $prev = wizard_helper_trail_previous($step, $object);
//      $next = wizard_helper_get_next_page($wizard, $prev);
//      $pages = array_keys($wizard['pages']);
//      $diff = array_intersect_key($pages, $wizard['object']['step_trail']);
//      $next_step = end($diff);
//      if ($diff != $wizard['object']['step_trail']) {
//        // Go to this page.
//        wizard_helper_goto($wizard, $next_step);
////        $wizard['object']['step_trail'] = $diff;
////        $wizard['object']['step'] = $next_step;
//      }
//    }
  }
}

/**
 * Wizard callback function.
 */
function wizard_helper_wizard($step = '', $js = '') {

  // Get the wizard information for this path.
  if ($wizard = wizard_helper_get_info()) {

    wizard_helper_set_context($wizard, $step, $js);

    // Remember the last page we were on.
    $previous_step = isset($wizard['object']['step']) ? $wizard['object']['step'] : '';

    // Make sure we are supposed to be on this page.
    $next_page = wizard_helper_get_next_page($wizard, $step);
    if ($next_page !== $step) {

      // See if this is in our pages array.
      if (isset($wizard['pages'][$next_page])) {

        // Go to this page.
        wizard_helper_goto($wizard, $next_page);
      }
      else {

        // Set the wizard form state.
        $wizard['form_state'] = array(
          'executed' => TRUE,
          'clicked_button' => array(
            '#wizard type' => $next_page
          ),
        );
      }
    }

    // Make sure the current page is in the step trail.
    wizard_helper_trail_add($wizard, $previous_step, $step);

    // Call the wizard callback to alter the info at runtime.
    if (isset($wizard['wizard callback'])) {
      $function = $wizard['wizard callback'];
      if (function_exists($function)) {
        $function($step, $wizard);
      }
    }

    // Make sure there are pages.
    if (empty($wizard['pages'])) {
      drupal_not_found();
      return;
    }

    // If there is already output, then return it here.
    if (!empty($wizard['output'])) {
      return $wizard['output'];
    }

    // Set the step.
    $wizard['object']['step'] = $step;

    // Set the cache so we have the $step we need.
    wizard_helper_cache_set($wizard, $wizard['object']);

    // Return the wizard helper form.
    return wizard_helper_form($wizard, $step, $js);
  }

  // Return 404 if we cannot find the information.
  drupal_not_found();
}

/**
 * Determines what the next page should be.
 *
 * @param array $wizard
 *   The wizard object.
 * @param string $step
 *   The current step.
 *
 * @return string
 *   The next step in the wizard.
 */
function wizard_helper_get_next_page($wizard, $step) {

  // Set the next and previous steps.
  $next_step = $prev_step = $step;

  // Iterate until the next step isn't a string.
  do {

    // Set the previous step.
    $prev_step = $next_step;

    // Check for an access function.
    ctools_form_include($form_state, $wizard['form id']. '_' . $next_step, $wizard['module'], $wizard['wizard path']);
    $access_function = $wizard['object name'] . '_' . $next_step . '_access';
    $next_step = function_exists($access_function) ? $access_function($wizard) : TRUE;

  } while (is_string($next_step));

  // Make sure we have access.
  if (empty($next_step) && ($prev_step === $step)) {
    drupal_access_denied();
    module_invoke_all('exit');
    exit();
  }
  else {

    // Set the step for this page.
    $next_step = $prev_step;
  }

  // Return the next step.
  return $next_step;
}

/**
 * Go to a page within the wizard without it resetting context.
 */
function wizard_helper_goto($wizard, $step = '') {

  // Make sure the current page is in the step trail.
  $previous_step = isset($wizard['object']['step']) ? $wizard['object']['step'] : '';
  wizard_helper_trail_add($wizard, $previous_step, $step);

  // Set the current step.
  $wizard['object']['step'] = $step;

  // Save the wizard.
  wizard_helper_cache_set($wizard, $wizard['object']);

  // Redirect.
  $path = $wizard['path'];
  $path .= $step ? '/' . $step : '';
  $query = $_GET;
  unset($query['q']);
  drupal_goto($path, $query);
}

/**
 * Gets the name of the cache.
 *
 * @param array $wizard
 *   The wizard data.
 * @param boolean $include_sid
 *   Whether the data should be exclusive to this session.
 *
 * @return string
 *   The registration cache name.
 */
function wizard_helper_cache_name($wizard, $include_sid = TRUE) {
  $name = $wizard['object name'];
  if (!empty($wizard['context id'])) {
    $name .= '_' . $wizard['context id'];
  }
  else if ($include_sid) {
    $session_id = session_id();
    if (!empty($session_id)) {
      $name .= '_' . $session_id;
    }
  }
  return $name;
}

/**
 * Get the object cache.
 *
 * @param array $wizard
 *   The wizard object.
 * @param string $_id
 *   The mongodb ID to load the cache explicitly.
 *
 * @return array
 *   The cached data array.
 */
function wizard_helper_cache_get($wizard, $_id = NULL) {

  $cid = wizard_helper_cache_name($wizard, empty($_id));

  if ($wizard['cache type'] == 'session') {
    $name = $wizard['object name'];
    $session = wizard_helper_session_exists($name);
    if ($session) {
      return $_SESSION[$name];
    }
  }
  else if ($wizard['cache type'] == 'cache') {
    $cache = cache_get($cid);

    if ($cache) {
      $document = $cache->data;
    }
  }
  // @todo: Find out why the session gets reset for every step which is why...
  // this creates multiple entries if using an ajax modal.
  else if ($wizard['cache type'] == 'ctools') {
    ctools_include('object-cache');
    // Get the ctools cache.
    $ctools_cache = ctools_object_cache_get($wizard['object name'], $wizard['object name']);

    if (!empty($ctools_cache)) {
      $document = $ctools_cache;
    }
  }
  else if ($wizard['cache type'] == 'mongo') {

    // Get the cache from mongo.
    $criteria = array(
      'wizard' => $cid,
    );
    if ($_id) {
      $criteria['_id'] = new MongoId($_id);
    }
    else {
      $criteria['sid'] = session_id();
      if (empty($criteria['sid'])) {
        return NULL;
      }
    }

    // Load the document.
    $collection = mongodb_collection($wizard['mongo_collection']);
    $document = $collection->findOne($criteria);

    if ($document) {
      $data = $document['data'];
      if (is_string($data)) {
        // Unserialize the main content.
        $data = unserialize($data);
      }
      unset($document['data']);

      if ($data) {
        // Merge the main content back into the document.
        $document = array_merge($data, $document);
      }
    }
  }

  // Nothing cached.
  if (empty($document)) {
    $document = array();
  }

  // Callback after loading data.
  if (!empty($wizard['wizard after load'])) {
    $wizard['wizard after load']($document);
  }

  return $document;
}

/**
 * Set the object cache.
 *
 * @param array $wizard
 *   The wizard object.
 * @param array $value
 *   The cached data to save.
 * @param boolean $save_sid
 *   If false, the data will be saved without a sid and can only be accessed
 *   with a direct link containing the mongo _id.
 */
function wizard_helper_cache_set($wizard, &$value, $save_sid = TRUE) {
  // Callback before saving data.
  $save_data = $value;

  if (!empty($wizard['wizard before save'])) {
    $wizard['wizard before save']($save_data);
  }

  $cid = wizard_helper_cache_name($wizard, $save_sid);

  if ($wizard['cache type'] == 'session') {
    $name = $wizard['object name'];
    wizard_helper_session_save($name, $value);
  }
  else if ($wizard['cache type'] == 'cache') {
    // Set the cache.
    cache_set($cid, $save_data);
  }
  // Use ctools object cache.
  else if ($wizard['cache type'] == 'ctools') {
    // If we haven't already added it, add the $cid to the cache. This allows us
    // to clear the object cache later by calling ctools_object_cache_get() and
    // targeting the specific cache.
    if (!isset($save_data['cache'])) {
      $save_data['cache'] = array('name' => $cid, 'obj' => $wizard['object name']);
    }
    ctools_include('object-cache');
    ctools_object_cache_set($wizard['object name'], $wizard['object name'], $save_data);
  }
  // Use mongo db.
  else if ($wizard['cache type'] == 'mongo') {

    $_id = (!empty($save_data['_id'])) ? $save_data['_id'] : NULL;

    // Unset values that are not serialized.
    unset($save_data['_id']);
    unset($save_data['sid']);
    unset($save_data['time']);

    // Set the wizard value.
    $wizard_id = !empty($save_data['wizard']) ? $save_data['wizard'] : $cid;
    unset($save_data['wizard']);

    // Update required values.
    $insert_value = array(
      'wizard' => $wizard_id,
      'time' => time(),
      'data' => serialize($save_data),
    );
    if ($save_sid) {
      $insert_value['sid'] = session_id();
    }

    // Initialize mongodb.
    $collection = mongodb_collection($wizard['mongo_collection']);

    if (!empty($_id)) {
      // Cache already exists, update it.
      $criteria = array('_id' => $_id);
      $collection->update($criteria, $insert_value);
    }
    else {
      // Create new cache.
      $collection->insert($insert_value);
      if (empty($insert_value['_id'])) {
        // TODO: This shouldn't be necessary if the insert query can wait for
        // the _id to be returned.
        $insert_value = $collection->findOne($insert_value);
      }
      $value['_id'] = $insert_value['_id'];
    }
  }
}

/**
 * Clear the object cache.
 *
 * @param array $wizard
 *   The wizard object.
 * @param string $_id
 *   The mongodb id. If supplied this item will be cleared
 *   otherwise the session id will be used.
 */
function wizard_helper_cache_clear($wizard, $_id = NULL) {

  $cid = wizard_helper_cache_name($wizard, empty($_id));

  if ($wizard['cache type'] == 'session') {
    wizard_helper_session_delete($wizard['object name']);
  }
  else if ($wizard['cache type'] == 'ctools') {
    ctools_include('object-cache');
    // Set the serialized data array to an empty array.
    ctools_object_cache_clear($wizard['object name'], $wizard['object name']);
  }
  else if ($wizard['cache type'] == 'mongo') {

    $criteria = array(
      'wizard' => $cid,
    );
    if ($_id) {
      $criteria['_id'] = new MongoId($_id);
    }
    else {
      $criteria['sid'] = session_id();
      if (empty($criteria['sid'])) {
        return FALSE;
      }
    }

    $collection = mongodb_collection('group_registration_cache');
    $collection->remove($criteria);
  }
}

/**
 * Callback for the proceed step.
 */
function wizard_helper_next(&$form_state) {
  $wizard = $form_state['wizard_info'];
  wizard_helper_cache_set($wizard, $form_state[$wizard['object name']]);
}

/**
 * Callback generated when the wizard is finished.
 */
function wizard_helper_finish(&$form_state) {
  $wizard = $form_state['wizard_info'];
  // Remove the cache object.
  if (empty($form_state['wizard_info']['save cache'])) {
    // @todo: uncomment this...
    wizard_helper_cache_clear($wizard);
  }
  else {
    wizard_helper_cache_set($wizard, $wizard['object']);
  }
  // Run finalization processes.
  $function = $wizard['wizard finish'];
  $file = DRUPAL_ROOT . '/' . $wizard['module path'] . '/' . $wizard['wizard finish'] . '.inc';
  // Try to include a file by the same name.
  if (file_exists($file)) {
    require_once($file);
  }
  if (function_exists($function)) {
    $function($form_state[$wizard['object name']]);
  }
  $form_state['complete'] = TRUE;
}

/**
 * Callback for the cancel.
 */
function wizard_helper_cancel(&$form_state) {
  $wizard = $form_state['wizard_info'];
  wizard_helper_cache_clear($wizard);
  $form_state['executed'] = TRUE;
  $form_state['cancel'] = TRUE;
  if (!empty($wizard['cancel message'])) {
    drupal_set_message($wizard['cancel message']);
  }

  $form_state['cancel'] = TRUE;

  // Call a callback for the wizard.
  if (isset($wizard['wizard cancel']) && is_callable($wizard['wizard cancel'])) {
    $wizard['wizard cancel']($wizard);
  }
}

/**
 * Add a new step to the trail, replacing future steps if the wizard is changing course.
 *
 * @param array $wizard
 *   The wizard object.
 * @param string $current_step
 *   The current step.
 * @param string $new_step
 *   The next page to add.
 *
 * @return boolean
 *   TRUE if the trail was actually modified.
 */
function wizard_helper_trail_add(&$wizard, $current_step, $new_step) {
  // If there is no step trail, then just add the new one.
  if (!isset($wizard['object']['step_trail'])) {
    $wizard['object']['step_trail'] = array($new_step);
    return TRUE;
  }

  // Find locate the steps in the trail.
  $current_step_id = array_search($current_step, $wizard['object']['step_trail']);
  $new_step_id = array_search($new_step, $wizard['object']['step_trail']);
  // If the next step is already in the trail, they just stepped back.
  if ($new_step_id !== FALSE) {
    return FALSE;
  }
  // If the previous page can't be found.
  elseif ($current_step_id === FALSE) {
    $wizard['object']['step_trail'][] = $new_step;
    return TRUE;
  }
  // If the next step in the trail is not the next step.
  elseif (
    $current_step != $new_step
    && (
      empty($wizard['object']['step_trail'][$current_step_id + 1])
      || $wizard['object']['step_trail'][$current_step_id + 1] != $new_step
    )
  ) {
    // Trim the trail and add the new step.
    array_splice($wizard['object']['step_trail'], $current_step_id + 1);
    $wizard['object']['step_trail'][] = $new_step;
    return TRUE;
  }
  return FALSE;
}

/**
 * Determine the step that was accessed prior to the current step.
 *
 * @param string $step
 *   The current step.
 * @param array $wizard
 *   The wizard object.
 *
 * @return string
 *   The step before the current step.
 */
function wizard_helper_trail_previous($step, $wizard) {
  if (empty($step) || empty($wizard['step_trail'])) {
    return NULL;
  }
  $current_step_id = array_search($step, $wizard['step_trail']);
  if ($current_step_id > 0) {
    return $wizard['step_trail'][$current_step_id - 1];
  }
  elseif (!empty($wizard['step_trail'][0])) {
    return $wizard['step_trail'][0];
  }
  else {
    return $step;
  }
}


function wizard_helper_session_save($object_id, $value) {

  if (!isset($_SESSION)) {
    drupal_session_start();
  }
  $_SESSION[$object_id] = $value;
}

function wizard_helper_session_exists($object_id) {

  return !empty($_SESSION[$object_id]);
}

function wizard_helper_session_delete($object_id) {

  unset($_SESSION[$object_id]);
}
